baseurl = "https://blog.ailistings.cn/"
defaultContentLanguage = "zh"
languageCode = "zh"
title = "Ai Listings Blog"
theme = "hugo-theme-dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "xiangmiangya"
description = "探索AI的未来——AiListings Blog。在这里，我们深入挖掘最新的AI工具和时事，为您提供一个全面的视角。从办公自动化到艺术创作，从学术研究到音乐合成，我们的blog涵盖了AI领域的各个方面。加入我们，一起见证人工智能如何塑造我们的世界。AiListings Blog——您的AI领域知识宝库。"
avatar = "img/avatar.png"
headerTitle = "Ai Listings Blog"
motto = "探索AI的未来——AiListings Blog"

# footerBottomText = ""

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2020

favicon = "img/favicon.ico"

# 代码高亮
highlightjs = true
highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
highlightjsExtraLanguages = ["ocaml"]
highlightjsTheme = "gruvbox-light"
highlightjsThemeDark = "gruvbox-dark"

# search
enableSearch = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
showSummaryCoverInPost = true
# showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"

